### ISSUE TITLE
PROXY怎么填写？

### ISSUE THREAD

**Issue by 514398473** [googidaddy/bili_upload_tool#16]
我有网络代理，但是不知道填写格式是什么？能举例下吗？

**Comment by googidaddy** [comment]
http://127.0.0.1:1234

**Comment by googidaddy** [comment]
> http://127.0.0.1:1234

例如我的是clash代理。http://127.0.0.1:7890

**Comment by 514398473** [comment]
感谢您的回答，填写好了，但是出现了如下错误：
api_1  | INFO:     Will watch for changes in these directories: ['/app']
api_1  | INFO:     Uvicorn running on http://0.0.0.0:20123 (Press CTRL+C to quit)
api_1  | INFO:     Started reloader process [1] using watchgod
web_1  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
api_1  | INFO:     Started server process [8]
api_1  | INFO:     Waiting for application startup.
api_1  | INFO:     Application startup complete.
api_1  | WARNING: [generic] The url doesn't specify the protocol, trying with http
api_1  | [youtube] XFX5bQZqXXs: Downloading webpage
api_1  | WARNING: [youtube] Unable to download webpage: <urlopen error [Errno 111] Connection refused>
api_1  | [youtube] XFX5bQZqXXs: Downloading android player API JSON
api_1  | WARNING: [youtube] <urlopen error [Errno 111] Connection refused>. Retrying ...
api_1  | [youtube] XFX5bQZqXXs: Downloading android player API JSON (retry #1)
api_1  | WARNING: [youtube] <urlopen error [Errno 111] Connection refused>. Retrying ...
api_1  | [youtube] XFX5bQZqXXs: Downloading android player API JSON (retry #2)
api_1  | WARNING: [youtube] <urlopen error [Errno 111] Connection refused>. Retrying ...
api_1  | [youtube] XFX5bQZqXXs: Downloading android player API JSON (retry #3)
api_1  | [youtube] XFX5bQZqXXs: Downloading iframe API JS
api_1  | WARNING: [youtube] Unable to download webpage: <urlopen error [Errno 111] Connection refused>
api_1  | [youtube] XFX5bQZqXXs: Downloading web player API JSON
api_1  | WARNING: [youtube] <urlopen error [Errno 111] Connection refused>. Retrying ...
api_1  | [youtube] XFX5bQZqXXs: Downloading web player API JSON (retry #1)
api_1  | WARNING: [youtube] <urlopen error [Errno 111] Connection refused>. Retrying ...
api_1  | [youtube] XFX5bQZqXXs: Downloading web player API JSON (retry #2)
api_1  | WARNING: [youtube] <urlopen error [Errno 111] Connection refused>. Retrying ...
api_1  | [youtube] XFX5bQZqXXs: Downloading web player API JSON (retry #3)
api_1  | WARNING: [youtube] Unable to download API page: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused')))
api_1  | ERROR: [youtube] XFX5bQZqXXs: Unable to download API page: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'))) (caused by URLError(ConnectionRefusedError(111, 'Connection refused')))
api_1  | ERROR: [youtube] XFX5bQZqXXs: Unable to download API page: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'))) (caused by URLError(ConnectionRefusedError(111, 'Connection refused')))
api_1  | INFO:     172.19.0.1:37720 - "POST /upload HTTP/1.1" 500 Internal Server Error
api_1  | ERROR:    Exception in ASGI application
api_1  | Traceback (most recent call last):
api_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
api_1  |     result = await app(self.scope, self.receive, self.send)
api_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
api_1  |     return await self.app(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 259, in __call__
api_1  |     await super().__call__(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
api_1  |     await self.middleware_stack(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
api_1  |     raise exc
api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
api_1  |     await self.app(scope, receive, _send)
api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
api_1  |     await self.simple_response(scope, receive, send, request_headers=headers)
api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
api_1  |     await self.app(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
api_1  |     raise exc
api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
api_1  |     await self.app(scope, receive, sender)
api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
api_1  |     raise e
api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
api_1  |     await self.app(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
api_1  |     await route.handle(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
api_1  |     await self.app(scope, receive, send)
api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
api_1  |     response = await func(request)
api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
api_1  |     raw_response = await run_endpoint_function(
api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
api_1  |     return await run_in_threadpool(dependant.call, **values)
api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
api_1  |     return await anyio.to_thread.run_sync(func, *args)
api_1  |   File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
api_1  |     return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
api_1  |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
api_1  |     return await future
api_1  |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
api_1  |     result = context.run(func, *args)
api_1  |   File "/app/./main.py", line 44, in upload
api_1  |     res = main(data.dict())
api_1  |   File "/app/./upload.py", line 16, in main
api_1  |     video_path = video_info.get("video_path")
api_1  | AttributeError: 'bool' object has no attribute 'get'



我的配置：
# Fill your secrets!
# 如果无PROXY，可留空
PROXY=http://127.0.0.1:7890
BILI_JCT=29381fxxxxxx
SESSDATA=c50300c3%2C1662xxxxx
BUVID3=554068C1-9174-3298-3824-xxxxx5865infoc

**Comment by googidaddy** [comment]
clash的话要开mixin，或者tun模式，把该装的虚拟网卡都装上，走全局代理

**Comment by 514398473** [comment]
感谢回答，我的电脑是ubuntu系统，安装的clash 没有这么多配置。
准备提桶跑路了。

**Comment by googidaddy** [comment]
> 

那应该用海外或者v2rayA

**Comment by googidaddy** [comment]
> > 
> 
> 那应该用海外服务器或者v2rayA

我也是ubuntu。clash配置雀实比windows繁琐

**Comment by 514398473** [comment]
换了v2rayA，开了全局代理，成功上传了一个，现在正在审核中。
感谢大佬！

**Comment by googidaddy** [comment]
okk

刘能 ***@***.***>于2022年3月17日 周四上午10:45写道：
