### ISSUE TITLE
开始运行时遇到问题

### ISSUE THREAD

**Issue by CabbCat** [googidaddy/bili_upload_tool#18]
运行后无法打开链接
![QQ截图20220516120321](https://user-images.githubusercontent.com/37258131/168512953-a63fe6c8-19c0-4f12-9a3b-191ce5cc318c.png)
不会程序没用过docker，请问测试用的yoursite:3000是需要将yoursite替换掉的吗？直接打开是无法访问...

**Comment by googidaddy** [comment]
yoursite指的是你服务器的ip,`服务器ip:3000`

**Comment by googidaddy** [comment]
第一个可能是连接不稳定，第二个像是成功了的样子

**Comment by CabbCat** [comment]
> 第一个可能是连接不稳定，第二个像是成功的样子，今晚回来之后我测一下。

好的，连接不稳定的话有没有可能是因为我服务器和win都不在国内的原因呢...

**Comment by googidaddy** [comment]
> > 第一个可能是连接不稳定，第二个像是成功的样子，今晚回来之后我测一下。
> 
> 好的，连接不稳定的话有没有可能是因为我服务器和win都不在国内的原因呢...
没多大关系。抱歉哈，明天再看，今天一天都在弄宽带

**Comment by CabbCat** [comment]
> > > 第一个可能是连接不稳定，第二个像是成功的样子，今晚回来之后我测一下。
> > 
> > 
> > 好的，连接不稳定的话有没有可能是因为我服务器和win都不在国内的原因呢...
> > 没多大关系。抱歉哈，明天再看，今天一天都在弄宽带

没事 大佬有空的时候看一下就行了 感谢orz

**Comment by googidaddy** [comment]
我今早新开了一个实例（DO新加坡区），正常部署运行，为了测试的目的，多搬了几个「doge」。
![zz](https://raw.githubusercontent.com/googidaddy/img/master/2022/20220518105516.png)
![xx](https://raw.githubusercontent.com/googidaddy/img/master/2022/20220518105549.png)
![yy](https://raw.githubusercontent.com/googidaddy/img/master/2022/20220518105909.png)
![uu](https://raw.githubusercontent.com/googidaddy/img/master/2022/20220518105934.png)
你的服务器可能当时网络不太稳，从代码出发的话，可以优化优化，应该重新上传2～3次（有空再更新维护）。

**Comment by CabbCat** [comment]
> 我今早新开了一个实例（DO新加坡区），正常部署运行，为了测试的目的，多搬了几个「doge」。 ![zz](https://raw.githubusercontent.com/googidaddy/img/master/2022/20220518105516.png) ![xx](https://raw.githubusercontent.com/googidaddy/img/master/2022/20220518105549.png) ![yy](https://raw.githubusercontent.com/googidaddy/img/master/2022/20220518105909.png) ![uu](https://raw.githubusercontent.com/googidaddy/img/master/2022/20220518105934.png) 你的服务器可能当时网络不太稳，从代码出发的话，可以优化优化，应该重新上传2～3次（有空再更新维护）。

感谢测试！
服务器那边我今天试了试好像还是一样的报错（打算暂时先不管那边了
反倒是电脑这边，不知道为什么 log和佬的一样但就是没上传上去...试了一下换视频和换号都一样orz

**Comment by CabbCat** [comment]
我就是在稿件中心刷新看不到上传中的稿件，很怪...

**Comment by googidaddy** [comment]
那真是鬼了，多上传几次看看，再把log看看。

**Comment by googidaddy** [comment]
no more info. closed
