### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by leeformoney** [googidaddy/bili_upload_tool#5]
点了上传，毫无反应

**Comment by googidaddy** [comment]
可以进docker（api）看看有无报错？提供深一步信息？我这边刚测试，结果是正常的。[123](https://raw.githubusercontent.com/googidaddy/img/master/img/20210907115457.png)，[333](https://raw.githubusercontent.com/googidaddy/img/master/img/20210907115526.png)

**Comment by googidaddy** [comment]
已更新，重新pull一下,修改必要配置然后部署。实测没问题！

> 点了上传，毫无反应
