### ISSUE TITLE
一些需求

### ISSUE THREAD

**Issue by limitcool** [googidaddy/bili_upload_tool#7]
1.将Cookie,ytdl代理等部分配置从前端存储至Yaml文件。
2.增加自动搬运,自动搬运一些频道的视频（定时遍历检测视频是否更新）。
3.增加前后端手动部署教程。

**Comment by googidaddy** [comment]
> 1.将Cookie,ytdl代理等部分配置从前端存储至Yaml文件。 2.增加自动搬运,自动搬运一些频道的视频（定时遍历检测视频是否更新）。 3.增加前后端手动部署教程。

更新了第一条，不过程序还有点bug（有时候thumbnail下载不来），需要微调一下，明天上班，有空再持续输出

**Comment by googidaddy** [comment]
all is done~
要关闭issue了
